# Pester-free contract check for sync-backend.ps1.
# Verifies preset-exact source selection, no silent fallback, and SHA-256 printing.
param([string]$SyncScript = (Join-Path $PSScriptRoot 'sync-backend.ps1'))
$ErrorActionPreference = 'Stop'

$syncScript = $SyncScript
if (-not (Test-Path -LiteralPath $syncScript)) {
    throw "sync-backend.ps1 not found next to verifier: $syncScript"
}

$failures = [System.Collections.Generic.List[string]]::new()
$checks = 0
function Assert-True {
    param([bool]$Condition, [string]$Message)
    $script:checks++
    if ($Condition) {
        Write-Host "PASS: $Message"
    } else {
        $script:failures.Add($Message) | Out-Null
        Write-Host "FAIL: $Message"
    }
}

. (Join-Path $PSScriptRoot 'backend-preset.ps1')
Assert-True ((Resolve-BackendPreset -DebugFlag 'true') -eq 'bottlemusic-check') 'explicit debug flag selects native Debug'
Assert-True ((Resolve-BackendPreset -DebugFlag 'false') -eq 'bottlemusic-release') 'explicit production flag selects native Release'
Assert-True ((Resolve-BackendPreset) -eq 'bottlemusic-check') 'manual backend build defaults to Debug'
Assert-True ((Resolve-BackendPreset -RequestedPreset 'bottlemusic-release' -DebugFlag 'true') -eq 'bottlemusic-release') 'explicit native preset takes priority'
$invalidDebugFlag = $false
try { Resolve-BackendPreset -DebugFlag 'unexpected' | Out-Null }
catch { $invalidDebugFlag = $true }
Assert-True $invalidDebugFlag 'unrecognized Tauri profile fails before building'

$uiRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$tauriConfig = [System.IO.File]::ReadAllText(
    (Join-Path $uiRoot 'src-tauri\tauri.conf.json'),
    [System.Text.Encoding]::UTF8
) | ConvertFrom-Json
$packageConfig = [System.IO.File]::ReadAllText(
    (Join-Path $uiRoot 'package.json'),
    [System.Text.Encoding]::UTF8
) | ConvertFrom-Json
Assert-True ($tauriConfig.build.beforeBuildCommand -eq 'pnpm backend:build:release && pnpm build') 'Tauri production command explicitly requests native Release'
Assert-True ($packageConfig.scripts.'backend:build:release' -match '-Preset\s+bottlemusic-release') 'release package script pins the native Release preset'

function Remove-VerificationSandbox {
    param([string]$Path)
    $tempRoot = [System.IO.Path]::GetFullPath($env:TEMP).TrimEnd('\') + '\'
    $resolved = [System.IO.Path]::GetFullPath($Path)
    if (-not $resolved.StartsWith($tempRoot, [System.StringComparison]::OrdinalIgnoreCase) -or
        -not ([System.IO.Path]::GetFileName($resolved).StartsWith('sync-verify-'))) {
        throw "Refusing to remove a path outside a verification sandbox: $resolved"
    }
    Remove-Item -LiteralPath $resolved -Recurse -Force -ErrorAction SilentlyContinue
}

function New-DummyFile {
    param([string]$Path, [string]$Content)
    $dir = Split-Path -Parent $Path
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    [System.IO.File]::WriteAllText($Path, $Content)
}

function Invoke-SyncInSandbox {
    param(
        [string]$SandboxRoot,
        [string]$Preset,
        [switch]$ExpectFailure,
        [switch]$StaleFingerprint
    )
    $sandboxSync = Join-Path $SandboxRoot 'ui\scripts\sync-backend.ps1'
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $sandboxSync) | Out-Null
    Copy-Item -LiteralPath $syncScript -Destination $sandboxSync -Force
    $identityScript = Join-Path $PSScriptRoot 'verify-native-runtime.ps1'
    Copy-Item -LiteralPath $identityScript -Destination (Join-Path (Split-Path -Parent $sandboxSync) 'verify-native-runtime.ps1')

    # Dummy runtimes carry a fingerprint generated by the production policy.
    # One fixture changes its source afterwards to reproduce a stale build.
    $nativeFixture = Join-Path $SandboxRoot 'native'
    $realCMake = [System.IO.File]::ReadAllText((Join-Path $PSScriptRoot '..\..\native\CMakeLists.txt'))
    $policyStart = $realCMake.IndexOf('# ECHO_NATIVE_FINGERPRINT_POLICY_BEGIN')
    $policyEndText = 'string(SHA256 ECHO_NATIVE_BUILD_HASH "${ECHO_NATIVE_BUILD_HASH}")'
    $policyEnd = $realCMake.IndexOf($policyEndText, $policyStart)
    $policy = $realCMake.Substring($policyStart, $policyEnd + $policyEndText.Length - $policyStart)
    New-DummyFile (Join-Path $nativeFixture 'CMakeLists.txt') $policy
    $fixtureHeader = Join-Path $nativeFixture 'core\fixture.h'
    New-DummyFile $fixtureHeader '// runtime source version one'
    $fingerprint = & $identityScript -NativeRoot $nativeFixture -FingerprintOnly
    foreach ($profile in @('bottlemusic-check', 'bottlemusic-release')) {
        $fixtureRuntime = Join-Path $nativeFixture "out\$profile\EchoCAPI.dll"
        if (Test-Path -LiteralPath $fixtureRuntime -PathType Leaf) {
            [System.IO.File]::AppendAllText($fixtureRuntime, "`n$fingerprint")
        }
    }
    if ($StaleFingerprint) { New-DummyFile $fixtureHeader '// changed after the DLL was built' }

    $outFile = Join-Path $SandboxRoot 'sync-out.txt'
    $errFile = Join-Path $SandboxRoot 'sync-err.txt'
    $proc = Start-Process -FilePath 'powershell.exe' -ArgumentList @(
        '-NoProfile',
        '-ExecutionPolicy', 'Bypass',
        '-File', $sandboxSync,
        '-Preset', $Preset
    ) -Wait -PassThru -RedirectStandardOutput $outFile -RedirectStandardError $errFile -WindowStyle Hidden

    $stdout = Get-Content -LiteralPath $outFile -Raw -ErrorAction SilentlyContinue
    $stderr = Get-Content -LiteralPath $errFile -Raw -ErrorAction SilentlyContinue
    if ($null -eq $stdout) { $stdout = '' }
    if ($null -eq $stderr) { $stderr = '' }
    $combined = $stdout + "`n" + $stderr

    if ($ExpectFailure) {
        Assert-True ($proc.ExitCode -ne 0) "preset=$Preset invalid or unavailable runtime must fail (exit=$($proc.ExitCode))"
    } else {
        Assert-True ($proc.ExitCode -eq 0) "preset=$Preset sync must succeed (exit=$($proc.ExitCode) err=$stderr)"
    }
    return [pscustomobject]@{
        ExitCode = $proc.ExitCode
        Output   = $combined
    }
}

function Get-Sha256 {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { return $null }
    return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash
}

function Get-FileText {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { return $null }
    return Get-Content -LiteralPath $Path -Raw
}

# --- Case 1: check preset copies only from check ---
$sandbox1 = Join-Path $env:TEMP ("sync-verify-check-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $sandbox1 | Out-Null
try {
    New-DummyFile (Join-Path $sandbox1 'native\out\bottlemusic-check\EchoCAPI.dll') 'CHECK-DLL-CONTENT-AAAA'
    New-DummyFile (Join-Path $sandbox1 'native\out\bottlemusic-release\EchoCAPI.dll') 'RELEASE-DLL-CONTENT-BBBB'
    New-DummyFile (Join-Path $sandbox1 'native\vcpkg_installed\x64-windows\bin\sqlite3.dll') 'SQLITE-DLL'
    New-DummyFile (Join-Path $sandbox1 'ui\src-tauri\target\release\EchoCAPI.dll') 'OLD-RELEASE-MUST-NOT-CHANGE'
    New-Item -ItemType Directory -Force -Path (Join-Path $sandbox1 'ui\src-tauri\libs') | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $sandbox1 'ui\src-tauri\target\debug') | Out-Null
    New-DummyFile (Join-Path $sandbox1 'ui\src-tauri\libs\EchoCAPI.dll') 'OLD-STAGED-RUNTIME'
    New-DummyFile (Join-Path $sandbox1 'ui\src-tauri\target\debug\EchoCAPI.dll') 'OLD-DEBUG-RUNTIME'

    $result = Invoke-SyncInSandbox -SandboxRoot $sandbox1 -Preset 'bottlemusic-check'
    $checkHash = Get-Sha256 (Join-Path $sandbox1 'native\out\bottlemusic-check\EchoCAPI.dll')
    $releaseHash = Get-Sha256 (Join-Path $sandbox1 'native\out\bottlemusic-release\EchoCAPI.dll')
    $staging = Join-Path $sandbox1 'ui\src-tauri\libs\EchoCAPI.dll'
    $debugDst = Join-Path $sandbox1 'ui\src-tauri\target\debug\EchoCAPI.dll'
    $releaseDst = Join-Path $sandbox1 'ui\src-tauri\target\release\EchoCAPI.dll'

    Assert-True (Test-Path -LiteralPath $staging) 'check sync writes staging EchoCAPI.dll'
    Assert-True (Test-Path -LiteralPath $debugDst) 'check sync writes target/debug EchoCAPI.dll'
    Assert-True ((Get-Sha256 $staging) -eq $checkHash) 'check staging hash equals check source'
    Assert-True ((Get-Sha256 $debugDst) -eq $checkHash) 'check debug hash equals check source'
    Assert-True ((Get-Sha256 $staging) -ne $releaseHash) 'check staging hash is not release hash'
    Assert-True ((Get-FileText $releaseDst) -eq 'OLD-RELEASE-MUST-NOT-CHANGE') 'check sync must not overwrite target/release'
    Assert-True ($result.Output -match [regex]::Escape((Join-Path $sandbox1 'native\out\bottlemusic-check\EchoCAPI.dll'))) 'check output prints source absolute path'
    Assert-True ($result.Output -match $checkHash) 'check output prints source SHA-256'
    Assert-True ($result.Output -match '\[native:identity\] source_fingerprint=') 'check runtime matches current source fingerprint'
    $sqliteDebug = Join-Path $sandbox1 'ui\src-tauri\target\debug\sqlite3.dll'
    $sqliteRelease = Join-Path $sandbox1 'ui\src-tauri\target\release\sqlite3.dll'
    Assert-True (Test-Path -LiteralPath $sqliteDebug) 'check sync copies sqlite3.dll to debug profile'
    Assert-True (-not (Test-Path -LiteralPath $sqliteRelease)) 'check sync must not copy sqlite3.dll to release profile'
}
finally {
    Remove-VerificationSandbox $sandbox1
}

# --- Case 2: release preset copies only from release ---
$sandbox2 = Join-Path $env:TEMP ("sync-verify-rel-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $sandbox2 | Out-Null
try {
    New-DummyFile (Join-Path $sandbox2 'native\out\bottlemusic-check\EchoCAPI.dll') 'CHECK-DLL-CONTENT-AAAA'
    New-DummyFile (Join-Path $sandbox2 'native\out\bottlemusic-release\EchoCAPI.dll') 'RELEASE-DLL-CONTENT-BBBB'
    New-DummyFile (Join-Path $sandbox2 'native\vcpkg_installed\x64-windows\bin\sqlite3.dll') 'SQLITE-DLL'
    New-DummyFile (Join-Path $sandbox2 'ui\src-tauri\target\debug\EchoCAPI.dll') 'OLD-DEBUG-MUST-NOT-CHANGE'
    New-Item -ItemType Directory -Force -Path (Join-Path $sandbox2 'ui\src-tauri\libs') | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $sandbox2 'ui\src-tauri\target\release') | Out-Null

    $result = Invoke-SyncInSandbox -SandboxRoot $sandbox2 -Preset 'bottlemusic-release'
    $checkHash = Get-Sha256 (Join-Path $sandbox2 'native\out\bottlemusic-check\EchoCAPI.dll')
    $releaseHash = Get-Sha256 (Join-Path $sandbox2 'native\out\bottlemusic-release\EchoCAPI.dll')
    $staging = Join-Path $sandbox2 'ui\src-tauri\libs\EchoCAPI.dll'
    $debugDst = Join-Path $sandbox2 'ui\src-tauri\target\debug\EchoCAPI.dll'
    $releaseDst = Join-Path $sandbox2 'ui\src-tauri\target\release\EchoCAPI.dll'

    Assert-True (Test-Path -LiteralPath $staging) 'release sync writes staging EchoCAPI.dll'
    Assert-True (Test-Path -LiteralPath $releaseDst) 'release sync writes target/release EchoCAPI.dll'
    Assert-True ((Get-Sha256 $staging) -eq $releaseHash) 'release staging hash equals release source'
    Assert-True ((Get-Sha256 $releaseDst) -eq $releaseHash) 'release dest hash equals release source'
    Assert-True ((Get-Sha256 $staging) -ne $checkHash) 'release staging hash is not check hash'
    Assert-True ((Get-FileText $debugDst) -eq 'OLD-DEBUG-MUST-NOT-CHANGE') 'release sync must not overwrite target/debug'
    Assert-True ($result.Output -match [regex]::Escape((Join-Path $sandbox2 'native\out\bottlemusic-release\EchoCAPI.dll'))) 'release output prints source absolute path'
    Assert-True ($result.Output -match $releaseHash) 'release output prints source SHA-256'
    Assert-True ($result.Output -match '\[native:identity\] source_fingerprint=') 'release runtime matches current source fingerprint'
    $sqliteDebug = Join-Path $sandbox2 'ui\src-tauri\target\debug\sqlite3.dll'
    $sqliteRelease = Join-Path $sandbox2 'ui\src-tauri\target\release\sqlite3.dll'
    Assert-True (Test-Path -LiteralPath $sqliteRelease) 'release sync copies sqlite3.dll to release profile'
    Assert-True (-not (Test-Path -LiteralPath $sqliteDebug)) 'release sync must not copy sqlite3.dll to debug profile'
}
finally {
    Remove-VerificationSandbox $sandbox2
}

# --- Case 3: specified preset missing must fail, no silent fallback ---
$sandbox3 = Join-Path $env:TEMP ("sync-verify-miss-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $sandbox3 | Out-Null
try {
    New-DummyFile (Join-Path $sandbox3 'native\out\bottlemusic-check\EchoCAPI.dll') 'CHECK-ONLY'
    New-Item -ItemType Directory -Force -Path (Join-Path $sandbox3 'ui\src-tauri\libs') | Out-Null
    $staging = Join-Path $sandbox3 'ui\src-tauri\libs\EchoCAPI.dll'

    $result = Invoke-SyncInSandbox -SandboxRoot $sandbox3 -Preset 'bottlemusic-release' -ExpectFailure
    Assert-True (-not (Test-Path -LiteralPath $staging)) 'missing release source must not copy check DLL into staging'
    Assert-True ($result.Output -match 'bottlemusic-release' -or $result.ExitCode -ne 0) 'missing release source error mentions preset or non-zero exit'
}
finally {
    Remove-VerificationSandbox $sandbox3
}

# --- Case 4: a previously staged SQLite DLL cannot hide a missing dependency ---
$sandbox4 = Join-Path $env:TEMP ("sync-verify-sqlite-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $sandbox4 | Out-Null
try {
    New-DummyFile (Join-Path $sandbox4 'native\out\bottlemusic-release\EchoCAPI.dll') 'NEW-RELEASE'
    $staging = Join-Path $sandbox4 'ui\src-tauri\libs\EchoCAPI.dll'
    $profile = Join-Path $sandbox4 'ui\src-tauri\target\release\EchoCAPI.dll'
    New-DummyFile $staging 'PREVIOUS-STAGING'
    New-DummyFile $profile 'PREVIOUS-PROFILE'
    New-DummyFile (Join-Path $sandbox4 'ui\src-tauri\libs\sqlite3.dll') 'STALE-DEPENDENCY'
    $result = Invoke-SyncInSandbox -SandboxRoot $sandbox4 -Preset 'bottlemusic-release' -ExpectFailure
    Assert-True ((Get-FileText $staging) -eq 'PREVIOUS-STAGING') 'missing SQLite preserves staged EchoCAPI'
    Assert-True ((Get-FileText $profile) -eq 'PREVIOUS-PROFILE') 'missing SQLite preserves profile EchoCAPI'
    Assert-True ($result.Output -match 'Required sqlite3.dll') 'missing SQLite reports the required runtime'
}
finally {
    Remove-VerificationSandbox $sandbox4
}

# --- Case 5: a running application can lock a runtime; failure must preserve it ---
$sandbox5 = Join-Path $env:TEMP ("sync-verify-locked-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $sandbox5 | Out-Null
try {
    New-DummyFile (Join-Path $sandbox5 'native\out\bottlemusic-release\EchoCAPI.dll') 'NEW-RELEASE'
    New-DummyFile (Join-Path $sandbox5 'native\vcpkg_installed\x64-windows\bin\sqlite3.dll') 'SQLITE'
    $staging = Join-Path $sandbox5 'ui\src-tauri\libs\EchoCAPI.dll'
    New-DummyFile $staging 'RUNNING-RUNTIME'
    $lock = [System.IO.File]::Open($staging, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::Read)
    try {
        $result = Invoke-SyncInSandbox -SandboxRoot $sandbox5 -Preset 'bottlemusic-release' -ExpectFailure
        Assert-True ((Get-FileText $staging) -eq 'RUNNING-RUNTIME') 'locked destination is never truncated or renamed'
        $temporaryFiles = @(Get-ChildItem -LiteralPath (Split-Path -Parent $staging) -Filter '.runtime-*.tmp')
        Assert-True ($temporaryFiles.Count -eq 0) 'failed replacement cleans its own staging file'
    }
    finally { $lock.Dispose() }
}
finally {
    Remove-VerificationSandbox $sandbox5
}

# --- Case 6: reject an empty dependency before replacing either EchoCAPI copy ---
$sandbox6 = Join-Path $env:TEMP ("sync-verify-empty-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $sandbox6 | Out-Null
try {
    New-DummyFile (Join-Path $sandbox6 'native\out\bottlemusic-release\EchoCAPI.dll') 'NEW-RELEASE'
    New-DummyFile (Join-Path $sandbox6 'native\vcpkg_installed\x64-windows\bin\sqlite3.dll') ''
    $staging = Join-Path $sandbox6 'ui\src-tauri\libs\EchoCAPI.dll'
    New-DummyFile $staging 'PREVIOUS-STAGING'
    $result = Invoke-SyncInSandbox -SandboxRoot $sandbox6 -Preset 'bottlemusic-release' -ExpectFailure
    Assert-True ((Get-FileText $staging) -eq 'PREVIOUS-STAGING') 'empty SQLite preserves staged EchoCAPI'
}
finally {
    Remove-VerificationSandbox $sandbox6
}

# --- Case 7: no SQLite source or staged copy must be a build failure ---
$sandbox7 = Join-Path $env:TEMP ("sync-verify-nosqlite-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $sandbox7 | Out-Null
try {
    New-DummyFile (Join-Path $sandbox7 'native\out\bottlemusic-release\EchoCAPI.dll') 'NEW-RELEASE'
    $staging = Join-Path $sandbox7 'ui\src-tauri\libs\EchoCAPI.dll'
    New-DummyFile $staging 'PREVIOUS-STAGING'
    $result = Invoke-SyncInSandbox -SandboxRoot $sandbox7 -Preset 'bottlemusic-release' -ExpectFailure
    Assert-True ((Get-FileText $staging) -eq 'PREVIOUS-STAGING') 'no SQLite source preserves staged EchoCAPI'
    Assert-True ($result.Output -match 'Required sqlite3.dll') 'no SQLite source is diagnosed before copy'
}
finally {
    Remove-VerificationSandbox $sandbox7
}

# --- Case 8: changed sources must reject an old runtime before either copy ---
$sandbox8 = Join-Path $env:TEMP ("sync-verify-stale-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $sandbox8 | Out-Null
try {
    New-DummyFile (Join-Path $sandbox8 'native\out\bottlemusic-release\EchoCAPI.dll') 'STALE-RELEASE'
    New-DummyFile (Join-Path $sandbox8 'native\vcpkg_installed\x64-windows\bin\sqlite3.dll') 'SQLITE'
    $staging = Join-Path $sandbox8 'ui\src-tauri\libs\EchoCAPI.dll'
    $profile = Join-Path $sandbox8 'ui\src-tauri\target\release\EchoCAPI.dll'
    New-DummyFile $staging 'PREVIOUS-STAGING'
    New-DummyFile $profile 'PREVIOUS-PROFILE'
    $result = Invoke-SyncInSandbox -SandboxRoot $sandbox8 -Preset 'bottlemusic-release' -ExpectFailure -StaleFingerprint
    Assert-True ((Get-FileText $staging) -eq 'PREVIOUS-STAGING') 'stale fingerprint preserves staged runtime'
    Assert-True ((Get-FileText $profile) -eq 'PREVIOUS-PROFILE') 'stale fingerprint preserves profile runtime'
    Assert-True ($result.Output -match 'native_source_fingerprint_mismatch') 'stale source identity reports a rebuild requirement'
    Assert-True (@(Get-ChildItem -LiteralPath (Split-Path -Parent $staging) -Filter '.runtime-*.tmp').Count -eq 0) 'stale source identity fails before staging a replacement'
}
finally {
    Remove-VerificationSandbox $sandbox8
}

Write-Host ''
if ($failures.Count -gt 0) {
    Write-Host "verify-sync-backend: $($failures.Count) of $checks failed"
    foreach ($f in $failures) { Write-Host "  - $f" }
    exit 1
}
Write-Host "verify-sync-backend: $checks checks passed"
exit 0
